apiVersion: ENC[AES256_GCM,data:mOs=,iv:SXghZYAlF9FF2r4PKoTwXacMEGedkScVlNTehLUpdxs=,tag:6WQgAuaOXzghBphbUwBVPQ==,type:str]
kind: ENC[AES256_GCM,data:ADF1dTd6,iv:+ZOfbJlM3bN1a3ex7Juv4luQ4Ep/m/LwwulWPkIoA3c=,tag:h2rntE0cRQvk7kMX64uSqA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RvhP9UyQeZvJwYn+ObKoguBJ21c=,iv:wcjQdR3t7PQTQlumV0Hb7/wKz0AvR5IxWhw2R32IZWo=,tag:9eILlGyWiPqmY6mi9C8VXw==,type:str]
    namespace: ENC[AES256_GCM,data:XoMP1llAUeHIpA==,iv:EnZ0BePvjB0b9a4+/09RGaa09H1hPKzx9nRlZ7M1WH8=,tag:PPwC3v3PFJ/kMrEmIpcHnA==,type:str]
type: ENC[AES256_GCM,data:VeYr965U,iv:fZfvx6o7DlWcMpo78elXF8H71w9e5RgYQlRGqGhUaGo=,tag:bE+6W+mKqEqlMlJb4DfNqg==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:WUdGBWk9tdMrG/5qu0fyOwL1djrbpNagFYDH558CNpxgarLOdQB6Kg==,iv:nyxC4H6Qq1JAAu3l/I5nS+NtmeLe45WYNpw7BbATHHY=,tag:y8Fk/e+fSXRkht1sU8Cawg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNFoweUd2d1pIZjh2M2dG
            WXdicUtrZTJRWWhwZXZEZ0tWS29TMlZxU0hZCmVJOFVLMnRMNXV4eG5STWVIWTRW
            bldvVWxGcnMyNVFFb3VxbExvTThUakUKLS0tIGRMRFBYUnRabjJPb2l1VkRFVEJz
            cXhjUGI3OGJDVDhEeEdrcXlJSy9DZlUKXPbvcq9IHtui4zsGmugq5/WbnakU/PkC
            IW2UjQdcRSXbY6XtyRkYEDbIX0u88xbURSRQ8FgZK/emyJa4ONB53g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T01:48:11Z"
    mac: ENC[AES256_GCM,data:93GBjTtfCXiRN5BPeqF3iOfMuvM01gVMkzSBeQLwe9AzplCmCzovrtkBRS4LJyAbHpBNh+FtCn6jV4G5vaREBjqHVGcVSiOVHsk16UQHR2l99EJI+3+9BzU8HHYRLxlcCbCZdEa27OOjeFfCBhWmiBLNmvEfccmslyChsP7wRzs=,iv:ozCdZZLCDYbHzoKlfjYiOyDklZc2bCSFU3wrKnqWgiM=,tag:lgt56qFZF4P/5XC5Rwx2+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
