apiVersion: ENC[AES256_GCM,data:DU0=,iv:D/1X/Jq2qeyOrhRTBWPTmAIA8/CP2v2r9jL3w8P5Y8c=,tag:Ggo+Tf0AN8WDrhnBy4cjjQ==,type:str]
kind: ENC[AES256_GCM,data:lFYJKTug,iv:hsTVHkLFpy3SAQq5dia9cry4lY/QiBhFV+3haUK4GPo=,tag:eCYnZy7OnLAIRIY2NTzXJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:99A+Y0C2CJsIP66kt77N0G2HyMI=,iv:BofdxytDaghNJh9TQ0jLYmm5T+DAru5K0LXffZZl87o=,tag:B3NliohJDls0F6Mh1gXQvA==,type:str]
    namespace: ENC[AES256_GCM,data:o4Bf5dyRd4xQQQ==,iv:doLYU+x7E2oPiELBCvG+e0IHEMU0KGm0jG1IdCanM8k=,tag:FzCKj8tU1CEnAZcl4gZnlg==,type:str]
type: ENC[AES256_GCM,data:gZq2iKZx,iv:z3qVUORJufU3airB+xdweCOJ5GLd00oMBwLCRduR824=,tag:s0SDC8FRGbvukU8pxJJSuA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:q4EZgm+AW9B+QlThEqy0Mehj7LAs4CzpnttOdHkCwRN84rihpmGUrA==,iv:gjixC2lUbb8oBHYt0QkCL8QuTIKAF4Wvk1Js2TciBhE=,tag:AwzM478wZsAgs5OR7U0CqQ==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMzc2RE9tRU91a29jUlZF
            WHNFQlpjeDhkQ014L25BZDVaaSsyNm16WEQ4CnQ1R3ZNRlRBQnZqRnJrMm0xL2Rr
            UTd0UWt1L2tGRVo2U2tad3Mza2p4bjgKLS0tIDhFNzhOZ1lmRklCL2ViYXc2RmE2
            UytwN1k1NmpwaXFJTnF4MTV3NmdLbFUK9onD0SEszvG91Ws9CsEbXqB5mpEWA+2O
            jECL4nhMEPoyv0wsnYbJSIu9410DkZb8sNbp3Dvmyxq+asC7JqZs8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T04:28:56Z"
    mac: ENC[AES256_GCM,data:yBTDea1Ykiconv27XoJarWS+LXjxq514S0bzq8wuMkk3ZzUmStwHfehspCHJemNQUMZ8PT4lmwpcwDCtbcxlfSXAAvVxxmKZxKCZFMuFdCZwW9P/f2RdHR//4lqhoVH11U9zYJ47e5XoSZtgGrKogG2JJITbTGTdQsz8Wtanc1s=,iv:KrAj7fsMAAvt8hb8IwmzKzj+V1d+7Ky/ZXD0i3uy7yY=,tag:icLwrLZbEmpwITS8nRIBSQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
