apiVersion: ENC[AES256_GCM,data:+Ss=,iv:u2slFUdcDEc8OwrKhhWj7w8aYI03wFv9KhAbLESbGU4=,tag:rkFjbJxfGrUAP1MIfANbtg==,type:str]
kind: ENC[AES256_GCM,data:HqdDgME+,iv:pKjrrQFK3yLbWT6/JxcXvXH541L3tqcOCbjPv1YFE9w=,tag:O+t3lco1/LXmt+yMpnwYTw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RJVukXpWlpeSlpPQ/hAoZd6sFgM=,iv:3mXPYensX95ecOQERiy2NMnblAr7u2docleMlbtcaLw=,tag:RpJVtXFOfVVEfceXsJV5Cw==,type:str]
    namespace: ENC[AES256_GCM,data:iWhIjYjcoL+igw==,iv:zRZM06WPSvrgbXa+Qi9A8HDwJxOTqqqvtciZLcfIQkY=,tag:bC9FSxtJVBsMM5LJUchudQ==,type:str]
type: ENC[AES256_GCM,data:yfHHUEeI,iv:r109d3AxAqp3LFkkO3vWxnl5y0kNzTExpkIxG/W6Tjw=,tag:4AueAwvQAADxHfntuywnbA==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:Lf3r5/NUlr9vyUES8jS0NnRIhBl/cdNMKxnAaxW94/xugY67Sx0eWw==,iv:KiOQj4OQov08lO475UQ/+0t7zIcztiOTtDSp1AqiMZM=,tag:/8fiH1g77exHj1+xDVSxkg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OHlaQXk4YmsvZGdXaFVN
            WkkydmMwNzFsbVNiZmR5TEhqV05abENJd0VvCjM3QnVWM3RMRUhmNXBxSndvY0Iv
            STNqUGNacHMxb1dUY05kdXJDZnJ1M3MKLS0tIE1CUGxab3E3RlpNcCt1V3BBZXhs
            eVNMTk1oY3hMR0V1aEtwVUpmaTcxVGcKV3jBYzeKK61VkIb1T7hZxtokABDhZdpj
            J8e2CHKNI3W361MCKfpmBggkDfoR1leqYIZxZOvaDPHN1ZvHqIy4iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:22:24Z"
    mac: ENC[AES256_GCM,data:heoBn35MzMk4Dqur0k3SZESXMcl7IM40xowaJohLFxSpcVDqCcg9gwA/lqZJgUlBV76FF+S8sLdaSXrXpoxpEwIIvEv8otaw5bpanUV0VUYDVuKwxzrgwgQgkh+OAP2k7YH+zXl4dKey0B60aXhVj0MXFYyza341c7xSGTAHovA=,iv:40YlSjVWaiCiW0tZ6cn1heHEzYhJ/4DJpxo8Cv5nZEI=,tag:/ucnoJ2ovlfVhr14n6fuJQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
