apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaresolverr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/felipemalacarne/saradomin.git
    targetRevision: HEAD
    path: kubernetes/apps/media/flaresolverr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
