apiVersion: ENC[AES256_GCM,data:kfA=,iv:8o5VQIakWgwIn5CjyFiezktZgTW2DErzLELy7BVZC0k=,tag:zyG+Y6p2aGehdLpcWxxdGg==,type:str]
kind: ENC[AES256_GCM,data:hU9G73JS,iv:4s4cyw+uclxdBss/QcTViwtN6rrdBLoWuRj/pOLT4fs=,tag:KUCP3fuDE8+Tavc1gUAuWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7Z8+2kFL0h4awtRnAOvpZw==,iv:XnXNPQiXPoHm/QxgrUWMwU88HdYPdDQCMrhOkUxsEfM=,tag:EE6kAVsSk+YxS/YDDxvZHw==,type:str]
    namespace: ENC[AES256_GCM,data:b/BSznU=,iv:uGNfmTxxGutnMGaYr1Wp/hSIGEnn6PcFDmxoBO9mz1M=,tag:GvdY+cXCoyPyd2UgOs51zQ==,type:str]
stringData:
    radarr_api_key: ENC[AES256_GCM,data:FrOJEEpWVl3sqbhBa40PtLO/w/XgV4AaWN0cUqlG9ng=,iv:4fZcL7oekzF6ruI8PLOnqy8n/RaT9PqKkSFbF7pViK0=,tag:dCuu9u96ceswn6dIVzfh8Q==,type:str]
    sonarr_api_key: ENC[AES256_GCM,data:OfICidNmJcM937GsRJKCivbw4Nz5dRLgu8nJkTj++uo=,iv:OoLZWjGqAd2XV8zVhBIx213/sWhQSGA1fR8O6cek9jc=,tag:NwDnw8d1oAG58CJuV5qdTw==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQzZUcUNaMFkvRTBidThT
            b0swVUdQT2xVYU5OMTFvWVJEak5hZEkxYUZ3ClBkSXBDTHJNZkVObzJSSFBZekw3
            U0hLNEJSNjFMZk0xcklHeFFUUlhweEkKLS0tIFN3RDlyN1piZFMvWjN3eWZZNDVu
            d1VEL1ZBWFI4YklwQUxta21PM1VWQnMKL9t9nWqROJyiGmnzNC8rKEMtYYYMVRgH
            QYaBQMuM408QlN+eCmvt45Z7UijLAlcHRMjx8jkUFIaK8AHGa+BBkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T17:24:03Z"
    mac: ENC[AES256_GCM,data:1Ud/a4BwPNGQBPphXcZpYkt8YT4L/6D8Yp7HfWT1jhFmG7foFJFjMW7Ver79Gy8xUaLi56Dg8y0vn1qAepM62VNIi3T+f94Vj24CKMqp/QAAz3K8I7nkSm6XOeeqFRyrgjxx3PicYt/dS/LMLMBL7dseCOe9S9rJ/H6j+V02txQ=,iv:znnGrURVn9txNNMah3wogztfucwWwwXIJKWxM66Ckyk=,tag:NiuJ3eeTheFZsAT2I0M5xw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
