apiVersion: ENC[AES256_GCM,data:LR0=,iv:68q133X4r62ynTKxmXJ2lRKp97x3kgpD3dQYoZos+T4=,tag:TTkVmDCTNT+NmaP+4Gpajg==,type:str]
kind: ENC[AES256_GCM,data:5t53fG5D,iv:/0PopEoe7ImLXpQuyKosFD920nJmqs0okZRCU0YTzOY=,tag:M2V4hvgDFdveS5mEx+qtUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8lpLmr3MaHpXZmCOa+wjqrOW,iv:DsDgq7CaAg4gHlkdoCiP7eZFZuM5HnuqljI3LbOwc5k=,tag:PzqkJ1h0BRXglueljR0jZA==,type:str]
    namespace: ENC[AES256_GCM,data:uf5kCZTnD+k=,iv:ICrtIzUf5GmHG/ccG0lzDsmDT8dGCJ93szLp+6CVz5U=,tag:NJi4Va3+eMrS0ZaqJ0x9Fg==,type:str]
type: ENC[AES256_GCM,data:KOmjlvo5,iv:w1us7tN5ApbEgYqIAs50/+VyCR0/2GCWLT3FZRC2yvY=,tag:Ww8tgax2f0b7xp7Ep9jyow==,type:str]
stringData:
    database_url: ENC[AES256_GCM,data:SlF6JWMh1E7HtKNieiA5iP9xNXgyGxVbLHrC7udZ0dfraivqf/uMZr00iyJPRrmKFPup4ObioS6wZZqfC7h8Enx3i5RMN6R92+KnX4wqtO5v+L4=,iv:kBh4HdjhCn0cYQSwsWG0S0XbmBnE6SWrygkVeh2imrc=,tag:xR0lDZcS57ruKOiD8252Pg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N2hRMXdiMC82ODY1NjIw
            RGY1a3F5N0dJY2I2T1RlWlYrUTRkQmQzSUhjClBtN29RYmJxN2orZk1qcGQ3aXFH
            SUdhSndGTFZiZ3hRYk81bTV2MWJaSjAKLS0tIHNVTWxIdE8xVitGUW53aXNoSk02
            ZHE2L1JMb2NRaUpMNmRJbldpWWNLVVkKOhq8CbW4aYV6DhdFn2QArgvmoQhO0Mgn
            00AHaDViucya3m97UQrJ5+dOIoyWwT1UbdM6cgaeeQwnd73oIyVOoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T04:35:59Z"
    mac: ENC[AES256_GCM,data:GoSo+wZwZBF1giE23tKbtUMKbAQmUu5jCwRngXS30fUTn/i6bm8eDczJgSvjLfNUV7/Cm945Jo2LokvV5psILLCM6Bhlx2ooHg9xX8Q9M1qkVDVcKRp1/zbgh34ri3ftp0F7DScWzODIb/8jYJi86fBrgeGh7IZPk4CVOg4Y9rg=,iv:J3hDzV5gTUhxCxwlTwgETeOqv9QVvMF9doS76OMgiy4=,tag:jQRMFzZ9dybeCZK2vjY2HQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
