apiVersion: ENC[AES256_GCM,data:Cww=,iv:6GdxD8ELENS/0aF9oRmRXe0FwcYjhM690oQ2egibA2g=,tag:juR+zR6RZnOy70ubRCADig==,type:str]
kind: ENC[AES256_GCM,data:wiFa4uHb,iv:rDRxtFk9Ca74LremKuQRn74XzZaOMdMSgfNuOv3jRMo=,tag:DHhAFnZx6FiNN5k4DAoATA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NfXAeqikbMnPGED0sKwDKKHz,iv:9wDowattm2fijJ7lkcQJEQZ+JzyDpjHCZv5htlMoVGY=,tag:i6iv4H4MNF8Hk1PUFUpgXw==,type:str]
    namespace: ENC[AES256_GCM,data:rJReDiqcwPw=,iv:q2ZDNQqCWC88Q5pPP/F9viiEAAX7IF+7Wq3ULE+ApsE=,tag:W12iGt7NzUXf0CKolvawxg==,type:str]
type: ENC[AES256_GCM,data:Cw5EQKib,iv:3e2S9ofyMCA8sYB3/kMAvefTrn66Att32hlZa3YwaSk=,tag:jLH9hA6zxqhdM4O1TSf/jg==,type:str]
stringData:
    database_url: ENC[AES256_GCM,data:4P2fpBaRslAwUVdOBLtqOvN6F41DXksEUkCxI3FR1KpvfPzWaKR3gmG2d4kCkcEHnWnK9+EhlMshegslI7T8eTORfTzA4rLCVkz84ussXIlwN3I=,iv:Z0XLPOxzNxJLdxcFV7qLz1Hse90wX0JwHApYvJPnmb4=,tag:xH7UXpSsv7AclZkcYUfr5Q==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUnJta3ZKSFhPVU9XK0tD
            KzJlUHExNU9HaTZ5eTFRNHYxTURWdlIvVDFnCm1DTDZnSlNnSnhHYWtpOG1RRDdl
            eWgvRFMrQ3lEdnpORTlTbm1hVTE1K2cKLS0tIEFFTDNETTRIRGhsY0FZU3dzZTFF
            RE1YRUtDR0RFUUNaaENIOVRxWGdMSTAKa+WtNh6QlUK+85hk4uPDLZ6tS/iBoDst
            rV5EhAJ0D1jrO+cIWZIwrolB5kejKVhWz//tm3ebK7Yv/mxPF1AYuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T17:24:03Z"
    mac: ENC[AES256_GCM,data:PUQMnlD7uM5/KkAFFfqFqzcanXBfJYQBdwRyAV7z7NNRD8zTRXR7N9IeaAu9DP/0ujl+UY9S7T9pW2Y4ER5if530p84f8p1ra5AZWz5HoKCTP1Ck4WFg8j4798DkQNVd5+fpmg7j2tzgNQGWU5PfgrDs1OmCLxuBibSq8DwI/LE=,iv:ej6yD8+J+qEWST/+ZCfPe3jntqUemk4iUz4l91IBY9E=,tag:eGTUH5S0iBC88/w0m6yMTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
