apiVersion: ENC[AES256_GCM,data:aCg=,iv:2nzObnTBT2dhFAqEn7rPP1S7OhEkonjiOSurHuvsPPY=,tag:HQpxeyi8XFB2drlodRLyEg==,type:str]
kind: ENC[AES256_GCM,data:JB/b1hK/,iv:XBRPh8AMOPqN6TooBwydVL6ggkxLI8leDdtM49sP4bI=,tag:bu/WyKt2+CnYm25QDUQTAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ldqg2KhtPGi88pu7HYyQzSeH,iv:+pTePTmuluYIt7y23F6k93ZyjOzOfH+j+76HlZ3cQW4=,tag:zhBfJaR97gKOsKVtF+gzTQ==,type:str]
    namespace: ENC[AES256_GCM,data:ky0EpjJHTKI=,iv:BoNBSSsG+ms2ehAQ7UY7seQZmt6vZs3+1tarBQUf+vg=,tag:kwQEnbS5qkQg8AeW9b2kBQ==,type:str]
type: ENC[AES256_GCM,data:wEJhbulH,iv:ucCP24hc7OxzZ+GBZ2jarcLl18nMRKKrgGtTfAS53Fs=,tag:vjP8wNvKpfVkLyistNp7kA==,type:str]
stringData:
    database_url: ENC[AES256_GCM,data:ZDLjuiKrN7zqYjmU44mVDZEWbmwrqjULOoFIJnQYeZSGCB4UA5/ktjJX0CYm5XiJg1ZHXluPIIfMFv65t4EkSAwXXbpfj8dOdTm6YqMILZbsov4=,iv:8nyxZTU3TSa7RfQ1H5z6fIVTIa9YfYesfZzD2ztPHMg=,tag:p44NnT71dSpNLF4x0Y/dBg==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByV09aYTFrcjB1WGxsRDNV
            OEMydGQ4QUZwVG9QcHAvTkV4ZVlBK25KV3dnCnppSnVwZ3o1WXcrN2QxRS9PeTQ5
            d3dUSmdvN0tyb015VW1lU1NVUEptZXcKLS0tIDVER2xDOHZaTjZrbElTS2dvcVha
            RENUcnhhcTRjTmR6dmFTYTNaU2VUckkKjYvmWZz81YZ3b47gk8fvqOjA4z7wJhIX
            sNV1I9qWqPDmQtYxQ1U5k0BiPNxbGHUtkPk5w0PNydGvcH9ySACQVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T04:03:12Z"
    mac: ENC[AES256_GCM,data:XaVVlUXqW2VOjU8uiI3+LowyO3PfFr0s6Tq7+mJGJkSR2/M39hYrevS4bcdNRPu727OjXoUEOl+EwcCgxVaUjTER5GLqi4MvwdqdLvzKyPfMBnm6LDX68VoXsok8dW/y7+uC/Vcbn8uGtoiyxXhjax3F0gYbpMpyXEdr7HlkgOE=,iv:6m3p1bXND5JXMSO4VeCSDljBquXiqsIMIVvKTuY2wJM=,tag:gXKiiHMMmwGLgKoAie3ypQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
