apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: networking
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: "America/Sao_Paulo"
            - name: DNSMASQ_LISTENING
              value: "all"
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-secret
                  key: webpassword
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: pihole-data
              mountPath: /etc/pihole
            - name: dnsmasq-saradomin
              mountPath: /etc/dnsmasq.d/02-saradomin.conf
              subPath: 02-saradomin.conf
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-pvc
        - name: dnsmasq-saradomin
          configMap:
            name: pihole-dnsmasq-saradomin
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-admin
  namespace: networking
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
    - port: 80
      targetPort: 80
