apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pvc.yaml
  - configmap-dnsmasq.yaml
  - ingress.yaml
  - service-dns.yaml
generators:
  - ksops.yaml
