apiVersion: ENC[AES256_GCM,data:vHw=,iv:XdKbhp6Rssl7UmoMDC3Qyrv7PmY0x61u8UfCaTNTJbQ=,tag:V/yExS3gFMkE5f3zzpkMnQ==,type:str]
kind: ENC[AES256_GCM,data:1juqMKgc,iv:fvfOBngVryySv7Z3p0XcHRX2IJorkmEEor30STJtwak=,tag:HwdsBrGw3gNMoJdB08tT0A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7LHfuYvzl0wAgmspLA==,iv:7P02x3DhRCvqVvH2XOBh5g5wVQpPgYxPIjcItkzEZL0=,tag:WK2mJjjwpmolWsFU59eVMw==,type:str]
    namespace: ENC[AES256_GCM,data:wiiG1kl+XfSvjw==,iv:wj1rCq3S0BssdzOSQ9MORkfvfWscsW5Bkbq4T2YTaDA=,tag:/IguRFxLZfSqJDwwlU3MIA==,type:str]
type: ENC[AES256_GCM,data:WlQxfVPR,iv:XO0++jvWV8L9bEyqGTz0BKaLLIWbVqoics7cVS/yetA=,tag:lZiP+qdXq1znYMZpAYADUg==,type:str]
stringData:
    webpassword: ENC[AES256_GCM,data:V6Kn/WNTLxm6xd/UnCU=,iv:ktmKwcziTh6KC5ccUjAIwq6h1W4t3deJD8B1f5/f8gA=,tag:0zc4xjw1WicH0c8vVkGuAQ==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYjZ5c0RmVWRRNEh4NXpl
            SHNJM2QzaGR6a002ZEw4K3RUazAzSDRuU0NrCnZtOU1pN3gvY0dhNmEzWHlKbEF0
            dXBneGIrSXo1VURKWUZ4dFE5UXJDaFkKLS0tIFFnMzhTZTJvaW9rSkY4VmFhNTQ5
            ZEVIbkxjNkZYdVBvMzFtNXhLMERPSjAK0v4Y5/LgdeOpraxrYYFqAKK6clmIi72g
            lbMzWECsvhQYyb6qS9WjyUBwdRmBazVLEraTNRPjoQO1hJPiS4+fZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T04:16:44Z"
    mac: ENC[AES256_GCM,data:RSpfTJyEwFhb9izHJnwH3169Gq/GtTvJIDMAwt+JmBkZArLug8bNUpz2wdMvj+L5wJmHO7nYaFChM+5gmiK+N7ArQhQccEKDEQDuws2PB3ZKg9smIXh6n507QhtfjWWfEXTBX6KzFytg+7WAh2wmzeX56S+n7GOySX1j5ShAXvA=,iv:EYJPaHEYgjfoJoGKDzXASNEpxnV5EjqT07nhKfL/UIE=,tag:K4597t9n86taYGmfj2QiAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
