apiVersion: ENC[AES256_GCM,data:fck=,iv:zsA+zni24FSgFiTfOMabyWiXjnTR9CxrnTbo19WK2LA=,tag:as/3bTokn8gIqGmzgL88wg==,type:str]
kind: ENC[AES256_GCM,data:TaZgZ2bJ,iv:yPH8NWB8nR1L3PluvdjtXgBqr+Z/Gi1pBZjfp4UT4MU=,tag:fuSpNLnnn1YCi8bEO4BROA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:br6zDvlTo8WQXkFP0g==,iv:EZPi3W9BEuWmIM1XotCGJxKhNR5/VrAH5AwJeXTLCsY=,tag:7HJmSDVOs+TMhwDd1QYccA==,type:str]
    namespace: ENC[AES256_GCM,data:VwVPFqYZcHsK8Q==,iv:BE/x5zRTV+JxJQ6DHXnZ/omEIZ6J+zl3G4QUsgyyTxo=,tag:clZoQ4eA3JJPFlvq4ZMAtA==,type:str]
type: ENC[AES256_GCM,data:PQB0bWuO,iv:eUEfWkcVZpROzX0zMJxdd04g9CfULLbHw5GAc5ulNrg=,tag:m0rvyuQ0OVQEAVu1VNTWNA==,type:str]
stringData:
    webpassword: ENC[AES256_GCM,data:cf70bTKI1BSPMc2oEpM=,iv:9TaBCTm4nAfSlD6HVw8zFDx/vz9EVS8JzxWZQiTFDEI=,tag:9IZXKeAdPPM2gpDHihdzEQ==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdTVNQXZwS3FPTThMaVU4
            UTdhd2IwMU4zU3pRZU9tSzlCajYyZ2xxc0NVCmZad3loUGJ4S2dPOHZSSTEvZm1j
            cmVLTVhRSm9vT2lrcGZTSHdKeU9ocW8KLS0tIDU3VDI2a29wV2c2VUs4UDZHa2Rs
            V1F3WUQ4dmt5aXRBYThOS1V4V20vOVkKn21JguFsYie8/plgYfMBbV3UDMADi+SL
            NdHwKzE2bYDRl7ZiifPiDLqzjBHiZvXneYMn5RZuCPFOl3DEOl7fqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T02:22:24Z"
    mac: ENC[AES256_GCM,data:Lo68SOnBxbjP7MptIeZhy8XQ2Kfv4b0La+y9apdwNb+asbWFwW7tM8MIA0L9fY7S4zlRosnxuejZWz/duTHd0zbHqJy6faj50/LytYtuc5yBIfqZvep6DNwpftSu6qTLIg9nTRHGM3j67UBoW1HfpHEA6aENTOfGogJkwh0h9lo=,iv:i2GY3ucsTXnKQG3dwEwdQwkfl/Q6HVX+wQQwv2oiJNw=,tag:eGgtM3X/nckbEEH6cFpHGA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
