apiVersion: ENC[AES256_GCM,data:m9M=,iv:i9cLzJD9i6WMDC9U5Jep1ddPotsZ6ufvGxzE91JCNWA=,tag:Y/cW0HWHFEIz9txitUWUCQ==,type:str]
kind: ENC[AES256_GCM,data:rzrOTQde,iv:sl1Ipp0PasNjqxaEs8+80KLFBckhKrRcky1176BPTTw=,tag:yMLhqC/lXSVB+a//LMX+9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kK9L5kk/SYbHdtf1cQ==,iv:tQtL3ROnxHsCBFqj710IOMQmsOMfqPx8pUqUXjqqw5s=,tag:wG+u1hCtrjT9KXujWUTGhQ==,type:str]
    namespace: ENC[AES256_GCM,data:hGhkycfhBre4bg==,iv:xANZ2E0rw4wmRsGQWxTYOu5J/6QVJRi+7ohDgcTZPE0=,tag:+WmR77EzfnGYAWGdsbOmBA==,type:str]
type: ENC[AES256_GCM,data:Qg8OmqEm,iv:X+4r1kRXR9krk6eLf2lK1yTovczDt1U1hHF7vnoyUW0=,tag:Dnt2S6+jZvMCkng7UOGaBw==,type:str]
stringData:
    webpassword: ENC[AES256_GCM,data:WoeAIn5zc9K78lTeF5g=,iv:+k6Sg9BV2JyTrg+W+KIRkRlNIGmXgOh4l7xzM4Uj2Zc=,tag:yAIKyWoEhrR6M6yXE5xHaw==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSEl4Z2ZWS2lEYVoxMm0z
            RDFVdGpoeEZ1dy83Um4yNWZuY3N1Y2tlN2dvCnRJOGZYRUZPUlh3V1c4T0ErNEN4
            WmlwMEREQVZEcWNmdFhIcE9OaHpGQ28KLS0tIHlzYWJhb05LZmg2d0tOWXJaWG5x
            L0hTSzV6d0ZINWZUNWF4WjRzTUVINjAKh8avRKjISdctoo6Upa8lDIUB9c4FlI10
            BCwDGuRXP8Mpz43P5zzGPMpAYVgcdJlbFnHOsXQTTpX1HhxUOFPnaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T17:24:03Z"
    mac: ENC[AES256_GCM,data:k93tlCdNOeqzFG7flZTvu8FrY0TuhZyIb/5YQxFxV123jRrpHHVu6egDXLN2rj3AtMDVBsbZKwzZWweX3XwzCaaYjW3yaTfEUJJq+yz71GRxBQjDQmSdXElY+v4o54ZNQOzvrtfHmmuVBk54XxVE9J0aV0X24Vsow3poTKCN7L0=,iv:0dDD7zRlyZu1aTfEBn4JxpNhUZT1ZEVf07XktOc4ITM=,tag:5JZqnDdPREaNfsydg+kzGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
