apiVersion: v1
kind: Service
metadata:
  name: exportarr
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: exportarr
  ports:
    - name: radarr
      port: 9707
      targetPort: 9707
    - name: sonarr
      port: 9708
      targetPort: 9708
    - name: prowlarr
      port: 9709
      targetPort: 9709
    - name: bazarr
      port: 9710
      targetPort: 9710
