apiVersion: ENC[AES256_GCM,data:bf8=,iv:H49q5IMX+bApV8LckuqATr+2k/w6p0szEp55rnIT8Lk=,tag:4OSu1BnnyBqZkXdHpRGNzQ==,type:str]
kind: ENC[AES256_GCM,data:FpPZlR1K,iv:ESc3L0HgumeJ5gzYG1iNqT5JrA4sS6vJYBgyjXcRxgY=,tag:hDdsdxATw7O02npwQjEudQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gPp66x1SAbgC8rD86VfxYpw=,iv:kuowTUoj8hd+ZFaGnJPzePyyU0XqaYUh8kHM7qJDCA8=,tag:U+zRA3YpmKtg5OffLh/syg==,type:str]
    namespace: ENC[AES256_GCM,data:7i9DTiqEJdb5aw==,iv:FOfYoct7O69CTzfB1YF30kO5oMR8jabMvmESKvsw8I0=,tag:B2Vp+3ocDkOzGR7xZGYrhg==,type:str]
type: ENC[AES256_GCM,data:5bxvp5LA,iv:79ju5gDnqdYOh6jAceQUDLiFxU7cgaeUKKpPn2gSLf8=,tag:djHBKm40gIlIS5VKFDh2Gg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:RqPTQZF8etP3LCCPVwoAXitXSaxbNfAxB+NVBqJJcDY0f4up4xIyct7X/vHVxH4lCgVJ+WmgbpJFKL3MjmCl4aGXJADxMKrhZoWEk+f92gB7ihGXsF0JRVFS/pjOD0qGxJL8JcxZhjzAHKIp1U2EG3C9aLY9WmtRY1ShJVRsOziREI5MO+0Bex0DR5Ld7GEocH8cE/QqYPlBNaElnSdIVvDTVgwchpDN4ZKJP+aLfC5AVIhisBHSbPp7CCjdaywQsikBy2T1kEh1AepwO+sdkpvBDXUdA7/lOOyBAGciEljfYDVc+j5pFVZLxuggd6Xq,iv:mZfdht1IQ7yiXEp4yk8j5rvltXtdbYcYXzwN7+ua/Og=,tag:r5bfw1m3CiiYeZsIFy03Vw==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbktJODhna1JWQ09lMm1z
            bVYxMll3Y3F4R2MwbjFEbkRMWlVlYnBZUHdVCk5SaFRVN054QnNWVGJYZkEzQXdz
            M3VaZWticExFS1JTdi9BWmFJQ0NreXMKLS0tIHFCMUlmM2Y1T21KUmFFLzFVaUVl
            UG9uTUVkWlFFYWdicHIyU0EvSmhQMmMKBKwLYsLaS+Ru7SiptSCYbpIx2HnTpZwS
            buX/xjUaj9nosekxWdPjD8wxgzIbJWEB5yIaWkeLe4A8/WUh+cE5AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T04:35:59Z"
    mac: ENC[AES256_GCM,data:ynDmPf2YJ+QJKl++uCk6Xi2dAa2nXjOhs7fzd4+ODJZ2azM1MU34Kzm8eZIlEk2TCCiGdE27moJinilL+vX64hsVWIWHiMdy3Wj10QeOCFBk1WQ/AEx3KpKRdQleEmvchwDqG3srQvRCMloxC+2L4U9eSYH/iZCocPntpsTrNVM=,iv:+HAntG6wKJUF2GNNYBFCMpyLNvLkc01cbEA/HXX2LQ0=,tag:Ede3/2q9eLFgatSxwpup3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
