apiVersion: ENC[AES256_GCM,data:Xls=,iv:Wl4Xil2FHF7+0j4x1NR7sMDOh0jWd8Z8JyI9b18h+aY=,tag:p6fjHYsc5fwx4Y1mxXlzxA==,type:str]
kind: ENC[AES256_GCM,data:5btZEuVO,iv:Btu9aAx+MwH3PxjnXY2jShG9oh6O2ZzUeFHtFnWpXkc=,tag:E28htU4WlvfYPtD3UWrc5A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BtaczHEfk9vPelXcrMbB9Zc=,iv:WrIvvIQ5tWQ2TCr1dcukXKpTv4/SltQUutnKq4e+vZE=,tag:XBD9Jmm2zi9x/cVCtglh4Q==,type:str]
    namespace: ENC[AES256_GCM,data:kY5LLjmZmq/dMQ==,iv:oZIOtzUVMB3UbqdVpWTUhYlo7DpI8X3G+BRAOGOdrrY=,tag:jwt1N7uoiBIjfo6pcFDKyw==,type:str]
type: ENC[AES256_GCM,data:QYX1zeGj,iv:l9FzS01KU2gM3U+3B9fS93EWXFK+SZEwEwQz9aAIzJI=,tag:cLSDziT+pfUcrBUPN60H2Q==,type:str]
stringData:
    token: ENC[AES256_GCM,data:hiIHAE2LKNmfnjrmH8f+wEhYQM0QssFxyQ/Qz7mCaXRK34sXPgMnu3YkKAPD3lIKLh5efTI0d4J9CzAiB9IdVqQz68Ic/xcrGc9LJ/H5p7SV+lcGWRY6YWYUz7dyxAZ3gOeWzA6RAz55JWRSyxxqmeCahBx/dOSDglzhu/U0+UXXnteeJOwAj5fL/n3Bq3uFRvg7ador8mTbvR379HvvcuzudqnM+DqbyWO+xMaqd0mxxSkOJgg2LnFL+6Lhy4/oUHgTpx1Qz/OOWatSwMsiq62WltBIOKh3HBrq8nZKvu4NGAfwQdaHQU1Z48QuJwwt,iv:cZ3HTYU58SeZIG5CHbjafrO/0/XETAti7H5lHZ7V9vo=,tag:oS7uVlQLgacQiHutd7lIwQ==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYi82Z3I5dnlsOHBxZXlk
            cDQ1SmFkcWtiYmFBcm1JNVVBeVF3RG9nM3hZCnBzelhCZmVOTmpFejl3T2ZjbkhD
            SGoxWkxaTkF3OTA2T0hEUG45WDNLSlEKLS0tIEJhTWZLMkRhckdwcUhrNE11YytU
            VUpvOEQ0OFlTbW5uSFVGOEtYb2tEY3cK2OJP3VMqGUvioNsll4qQmntppWVu1/xt
            s70iaNShJUQM0GPsDIaDPhE9mGc+avri3Lg03wJpDe2PKU6E4RUC2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T04:16:44Z"
    mac: ENC[AES256_GCM,data:AHgA2HwHA83ClkEPg6LbzuOMFN/C0OTDurvGXc09MWcnL5J0o4lBklwKQhTcX/L/EQ982d9Zp4L5IT5FvVqs1KXxr6sIqlNm/mlp43kYf8slPN1M4ZY5ChHQDxrVMVKhnOC6EFxGY7L9ULmQHcAiOO+Cmo0VI8Xas+r6XWa5Cq0=,iv:Wl4D0hjMZPLDdufroCBCidNhII+xtR40ZoUss7ZfVPE=,tag:0FgLAsdfDa5oy/MtrDPsYQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
