apiVersion: ENC[AES256_GCM,data:AcE=,iv:ny3ZkyHq0JFN7T+jV0NonwPBz+2CsWNnSXNShb/cBDU=,tag:hPDGm99odhsM7SqkRfQV7A==,type:str]
kind: ENC[AES256_GCM,data:/hKEp2mT,iv:SgmEuHYUAbbSJAjqU7EpJgrXaeA6WWYiAWLBs9SvBQY=,tag:aIZoCEetNPCiFGKniTUv5w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HskP/eY7IwXIh4boCWjBAF8=,iv:qKb24r8Ba6vAKR5aogZ3uXduuSXhd4ZUys2zp9iF2mE=,tag:mrW/TyyhS0P1TrbqwnOR5w==,type:str]
    namespace: ENC[AES256_GCM,data:BG3ZCoup8lGTXg==,iv:YmtBt0vg7ks/t1tRlHsoBuwXYJQxEFQ/GjJ2Dh7AKgU=,tag:KijTzB8HnwFSXjmiQQiWgg==,type:str]
type: ENC[AES256_GCM,data:3mP49lom,iv:OHtbUtCuqMG1FOBTVv095mGfHmTXwbHA5Ae2VW9TVSE=,tag:ehtWPgSzl09mCeuv7L7O4g==,type:str]
stringData:
    token: ENC[AES256_GCM,data:h/KsL294ySCcnl6bYxGZKL5B3QVm7sAbrzSxD+Ufs5NxyL/DPArpufh98Ww86l1Wt9lQDCZFK+6Mqc7mzDXzVlP859+5Ig+bFDSuKxSrpNC0qUX3TJhqSWmc0foC1j6DZCCOc+FiWKmVvpVVXwJDjM5Eryvp1QcmeSntPh5HeA1t0KtKX56TwoJB9tz/GjdNM6C9i35qcdOO42PixM1jGrSxDgaMqQnFiH3vHrn8p7m1uflD8wXBtNuTcazrFiLx0w9y0NHYQFQrBobp+ifAANPFexoJ10W94dgq0hmwALi/UmIJ8kEBx9/c9SpHzQWg,iv:NS19H6SjrdoWEWAXMnjpht6y/VHck2yH2Am+uDngTa4=,tag:4HUPQ3eUdbRgqADlLDpUpQ==,type:str]
sops:
    age:
        - recipient: age1pmynkgua3lfr2scfmd0h4xsgj7khehuxchunah54gur0u45lv53sd048gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZHQvNWVPeksvTGhzRWZF
            emdCa1B0VTNOd0RBYzVMc1BQSzIvdXVmMUhRCkE2ckxSamZZK0dOUjdsWmFXREd5
            ZjM0T2Nla1haVXRkdm00ajJMQmtObHcKLS0tIDZyUVdjdFJTM1dUZ0psOEt0a1pO
            VFo1bWhYU1g3TUUvR2pSU2c0MUxSMWsKrAj3lghvpMdkls+gMusTBKj2sKSYO9LS
            /1gfqVdNTVTzf1JLRkOttqzb1Fjkd95plRnegb2SD0Iuc7Fp0w/bJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T04:28:56Z"
    mac: ENC[AES256_GCM,data:gDxzuQo5TZotuCsQeKtcI8swCuny30a3psaRnYITrw2hGJ1aj77QqNV1ZDiALU2T4o/1a+Y8Y23YmRBD2nv0h3qmOtcghTInTavpt/H31rmzPIkUscPqJNi0SpscqNdcgjCSca+5vgsv1b93UIUxdysUu5KdEBM+pVpa3xfQkF0=,iv:+cJesnDmcLMU2PO9bsycgs5xdW3AZ3kGGFMBpglp5v4=,tag:UdqgejxhR4KvovpQU+296g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
